version: '3'

services:
  graphtoy-plus:
    restart: always
    container_name: graphtoy-plus
    build:
      context: .
    networks:
      - web
    environment:
      NODE_ENV: 'production'
    labels:
      traefik.docker.network: 'web'
      traefik.enable: 'true'
      traefik.backend: 'graphtoy-plus'
      traefik.frontend.rule: 'Host:graphtoy.csprance.com,www.graphtoy.csprance.com'
      traefik.port: '3000'

networks:
  web:
    external: true
